# Generated by Django 5.1.6 on 2025-02-06 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.job')),
            ],
            options={
                'unique_together': {('client', 'job')},
            },
        ),
    ]
